# Generated by Django 4.2 on 2023-10-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_choice_text'),
        ('polls', '0003_alter_question_pub_date'),
    ]

    operations = [
    ]
